baseurl = "http://www.jeremyelkayam.com"
title = "Jeremy Elkayam"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Jeremy N. Elkayam"
    info = "Thing Maker"
    description = "Personal website and blog for Jeremy Elkayam"
    keywords = "jeremy,elkayam,blog,developer,personal,software,editor,editing,animation,animator,programming,programmer"
    avatarurl = "images/headshot.jpeg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    #footercontent = "Footer text"

    hidecredits = true
    hidecopyright = false
    since = 2020

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jeremyelkayam/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/jeremy-elkayam"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 100
    url = "mailto:jne@jeremyelkayam.com"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 30
    url = "https://twitter.com/jeremyelkayam/"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube fa-2x"
    weight = 33
    url = "https://www.youtube.com/channel/UCYz2p3gsVARkk-GSjdZSijg"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 100
    url = "about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects/"